language: node_js
node_js:
  - "6.9"

before_install:
  - npm install -g yarn --cache-min 999999999

install:
  - yarn install

script: 
  - cd ./tests && yarn test

# # safelist
# branches:
#   only:
#   - master